# Generated by Django 2.1.1 on 2018-09-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdinaryUserInfo',
            new_name='UserInfo',
        ),
        migrations.DeleteModel(
            name='SystemUserInfo',
        ),
    ]
