# Generated by Django 2.1.1 on 2018-09-13 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warningtype', models.CharField(max_length=20)),
                ('warningcontent', models.CharField(max_length=100)),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
    ]
